export const restroList = [
  { "name": "KFC", "rating": "4.1", "deliveryTime": "35 minutes", "id": 1, "promoted": false },
  { "name": "Pizza Hut", "rating": "4.3", "deliveryTime": "30 minutes", "id": 2, "promoted": true },
  { "name": "Subway", "rating": "4.0", "deliveryTime": "25 minutes", "id": 3, "promoted": false },
  { "name": "Starbucks", "rating": "4.6", "deliveryTime": "20 minutes", "id": 4, "promoted": true },
  { "name": "Domino's Pizza", "rating": "4.2", "deliveryTime": "40 minutes", "id": 5, "promoted": false },
  { "name": "Burger King", "rating": "4.4", "deliveryTime": "35 minutes", "id": 6, "promoted": true },
  { "name": "Taco Bell", "rating": "4.3", "deliveryTime": "45 minutes", "id": 7, "promoted": false },
  { "name": "Insta Mart", "rating": "4.5", "deliveryTime": "30 minutes", "id": 8, "promoted": true },
  { "name": "Pasta Paradise", "rating": "3.8", "deliveryTime": "25 minutes", "id": 9, "promoted": false },
  { "name": "Sushi World", "rating": "4.7", "deliveryTime": "50 minutes", "id": 10, "promoted": true },
  { "name": "Ice Cream Corner", "rating": "3.9", "deliveryTime": "20 minutes", "id": 11, "promoted": false },
  { "name": "Chai Point", "rating": "4.1", "deliveryTime": "15 minutes", "id": 12, "promoted": true },
  { "name": "The Great Indian Biryani", "rating": "4.8", "deliveryTime": "60 minutes", "id": 13, "promoted": true },
  { "name": "Juice Junction", "rating": "3.7", "deliveryTime": "25 minutes", "id": 14, "promoted": false },
  { "name": "Waffle Wonders", "rating": "4.5", "deliveryTime": "30 minutes", "id": 15, "promoted": true },
  { "name": "Cupcake Corner", "rating": "4.3", "deliveryTime": "25 minutes", "id": 16, "promoted": false },
  { "name": "Fried Chicken Express", "rating": "4.6", "deliveryTime": "35 minutes", "id": 17, "promoted": true },
  { "name": "Healthy Salads Co.", "rating": "4.2", "deliveryTime": "40 minutes", "id": 18, "promoted": false },
  { "name": "Mexican Fiesta", "rating": "4.0", "deliveryTime": "45 minutes", "id": 19, "promoted": false },
  { "name": "The Breakfast Club", "rating": "4.5", "deliveryTime": "20 minutes", "id": 20, "promoted": true },
  { "name": "BBQ Nation", "rating": "4.7", "deliveryTime": "50 minutes", "id": 21, "promoted": true },
  { "name": "The Curry House", "rating": "4.4", "deliveryTime": "35 minutes", "id": 22, "promoted": false },
  { "name": "Chinese Wok", "rating": "4.1", "deliveryTime": "30 minutes", "id": 23, "promoted": false },
  { "name": "Mediterranean Magic", "rating": "4.2", "deliveryTime": "40 minutes", "id": 24, "promoted": false },
  { "name": "Raghu's Tea Stall", "rating": "3.6", "deliveryTime": "15 minutes", "id": 25, "promoted": false },
  { "name": "The Dessert Place", "rating": "4.3", "deliveryTime": "25 minutes", "id": 26, "promoted": false },
  { "name": "Pancake Parlour", "rating": "4.5", "deliveryTime": "30 minutes", "id": 27, "promoted": true },
  { "name": "Tandoori Tales", "rating": "4.6", "deliveryTime": "40 minutes", "id": 28, "promoted": true },
  { "name": "Noodle House", "rating": "4.2", "deliveryTime": "35 minutes", "id": 29, "promoted": false },
  { "name": "Momo Mania", "rating": "3.9", "deliveryTime": "20 minutes", "id": 30, "promoted": false },
  { "name": "Indian Sweets", "rating": "4.7", "deliveryTime": "50 minutes", "id": 31, "promoted": true },
  { "name": "Juicy Burgers", "rating": "4.3", "deliveryTime": "35 minutes", "id": 32, "promoted": true },
  { "name": "Thai Delights", "rating": "4.4", "deliveryTime": "40 minutes", "id": 33, "promoted": false },
  { "name": "Pizza Mania", "rating": "4.5", "deliveryTime": "25 minutes", "id": 34, "promoted": true },
  { "name": "Famous Falafel", "rating": "4.0", "deliveryTime": "30 minutes", "id": 35, "promoted": false },
  { "name": "Biryani Blues", "rating": "4.6", "deliveryTime": "45 minutes", "id": 36, "promoted": true },

];
